Login
Crazyfilip/Uceni_jazyku pull request #2
Opened 2019-07-28 11:14 UTC by Crazyfilip

2019-09-10 16:01 UTC, jirka-x1 requested changes
Jak pisu nize: Pridejte ke vsem tridam a metodam zakladni komentare a la javadoc.

2019-09-10 16:01 UTC, jirka-x1 commented on Uceni_jazyku/User_database/User_account.cs
> +namespace Uceni_jazyku.User_database
Pridejte ke vsem tridam a metodam zakladni komentare a la javadoc.

2019-09-10 16:01 UTC, jirka-x1 commented on Uceni_jazyku/User_database/User_account.cs
> +            if (!File.Exists("./users/accounts.txt"))
sem pridejte komentar ze je to narychlo a docasne - predpokladam, ze nechcete mi otevrena hesla v souboru i ve finalni verzi (nema pro tohle .NET nejakou podporu?)

2019-09-10 16:01 UTC, jirka-x1 commented on Uceni_jazyku/User_database/User_account.cs
> +            StreamReader reader = new StreamReader("./users/accounts.txt");
Nevim jak je to presne v .netu, ale nemel byste tu pouzit `using`? Jak se jinak zavre reader kdyz se vraci `true` nebo vznikne vyjimka?  Podobne vsude jinde, kde pouzivate soubory/readers/writers/...

2019-09-10 16:01 UTC, jirka-x1 commented on User_interface/LoginPage.cs
> +                MessageBox.Show("Přihlášení neúspěšné. Špatné uživatelské údaje.");
Predpokladam, ze planujete vsechny I18N texty mit v nejakych resourcech.

2019-09-11 20:48 UTC, Crazyfilip commented on Uceni_jazyku/User_database/User_account.cs
> +            if (!File.Exists("./users/accounts.txt"))
V google docs jsem napsal, že to je dočasné, ale komentář o tom patří i do kódu.

2019-09-11 20:48 UTC, Crazyfilip commented on Uceni_jazyku/User_database/User_account.cs
> +namespace Uceni_jazyku.User_database
Udělám.

2019-09-11 20:51 UTC, Crazyfilip commented on Uceni_jazyku/User_database/User_account.cs
> +            StreamReader reader = new StreamReader("./users/accounts.txt");
Celkově zápasím s tím, že po té dlouhé pauze mi mnoho věcí o C# vypadlo. Přepíšu to na to ten lepší přístup.

2019-09-11 20:52 UTC, Crazyfilip commented on User_interface/LoginPage.cs
> +                MessageBox.Show("Přihlášení neúspěšné. Špatné uživatelské údaje.");
Ano, lepší práci s resources plánuji pro druhou verzi

2019-09-18 06:04 UTC, jirka-x1 approved these changes

2019-09-18 06:06 UTC, jirka-x1 approved these changes

2019-10-13 10:07 UTC, merged